name: sentencepiece_dart_bindings
description: A Dart wrapper for the SentencePiece tokenizer.
version: 1.0.0

environment:
  sdk: ^3.3.3

dependencies:
  ffi:
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  ffigen: 

ffigen:
  output: 'lib/src/sentencepiece_dart_bindings.g.dart'
  headers:
    entry-points:
      - 'native/include/SentencePieceTokenizerCApi.h'
    include-directives:
      - 'native/include/SentencePieceTokenizerCApi.h'
  ffi-native:
    assetId: "package:sentencepiece_dart_bindings/sentencepiece_dart_bindings.dart"
  ignore-source-errors: true